/**
 * The icons a tag can wear: Material Symbols ligature names, drawn by
 * `components/ui/icon.tsx` from the self-hosted font. A curated grid rather
 * than the whole font, so the picker fits on a phone and every name is one
 * that has been seen to render.
 */
export const TAG_ICONS: string[] = [
  'work',
  'home',
  'person',
  'group',
  'favorite',
  'star',
  'flag',
  'bolt',
  'school',
  'menu_book',
  'edit',
  'code',
  'computer',
  'smartphone',
  'call',
  'mail',
  'chat',
  'event',
  'schedule',
  'alarm',
  'fitness_center',
  'directions_run',
  'self_improvement',
  'bedtime',
  'restaurant',
  'local_cafe',
  'shopping_cart',
  'local_grocery_store',
  'payments',
  'savings',
  'account_balance',
  'receipt_long',
  'medical_services',
  'medication',
  'pets',
  'child_care',
  'flight',
  'directions_car',
  'train',
  'hiking',
  'park',
  'water_drop',
  'music_note',
  'movie',
  'sports_esports',
  'palette',
  'build',
  'cleaning_services',
];
